### ISSUE TITLE
fix window.ethereum error

### ISSUE THREAD

**Issue by malteish** [dm3-org/dm3-ds-setup-helper#1]
![image](https://github.com/dm3-org/dm3-ds-setup-helper/assets/102788938/8cc77ac2-1e8d-48a7-8237-5409399e1ec0)

When navigating to a different tab in chrome and then returning to the helper tab, I see this error. It disappears on reload, but so do all inputs and the state. This is very unfortunate and must be fixed.

**Comment by Bhupesh-mfsi** [comment]
Fixed
