### ISSUE TITLE
Allow reload after saving env

### ISSUE THREAD

**Issue by malteish** [dm3-org/dm3-ds-setup-helper#3]
Currently, publishing the profile uses the information generated in step 1. That means the sensitive key pairs are still in memory. If a user performs step 1 and 2 offline, they should be able to completely wipe their browser memory before doing step 3. 
To do that, do something like this:
1. add an input `profileInput` to step 3
2. Auto-populate it from step 1
3. Allow the user to paste their profile, which they can copy from their .env file
4. Publish the profile from this input 

Update:
This approach allows Alice to do step 1 and 2 on her very secure airgapped machine, and complete step 3 on a machine that is online, but never sees sensitive information. At the same time, Bob, who is more interested in convenience, can do all steps on his laptop and be a happy dm3 DS operator.

**Comment by Bhupesh-mfsi** [comment]
Done
