### ISSUE TITLE
Validate inputs

### ISSUE THREAD

**Issue by malteish** [dm3-org/dm3-ds-setup-helper#4]
Currently, none of the inputs are validated. Suggested validations:
1. ens has valid format and is registered
2. url starts with https and has valid format
3. rpc has valid format or is empty (if empty: inform the user they can paste it into the .env file later)
4. before publishing profile, check if the account connected has the right to add records to this ens name
5. ...?

**Comment by malteish** [comment]
What to validate against

## ENS
- has at least 3 digits before dot
- has dot
- has "eth" after dot

## URL
- starts with http:// or https://
- has at least one digit after that

Background: local test setups can use http://a as valid URL

## RPC
either:
- is empty

or:
- starts with http:// or https://
- has at least one digit after that

**Comment by Bhupesh-mfsi** [comment]
> What to validate against
> 
> ## ENS
> * has at least 3 digits before dot
> * has dot
> * has "eth" after dot
> 
> ## URL
> * starts with http:// or https://
> * has at least one digit after that
> 
> Background: local test setups can use http://a as valid URL
> 
> ## RPC
> either:
> 
> * is empty
> 
> or:
> 
> * starts with http:// or https://
> * has at least one digit after that

@malteish Instead of checking the condition specific for valid ens name, we can directly use the **isValidName** method provided by **ethers library**. So I am using that directly. If there is anything wrong here, please let me know.
https://docs.ethers.org/v6/single-page/#isValidName

**Comment by Bhupesh-mfsi** [comment]
> Currently, none of the inputs are validated. Suggested validations:
> 
> 1. ens has valid format and is registered
> 2. url starts with https and has valid format
> 3. rpc has valid format or is empty (if empty: inform the user they can paste it into the .env file later)
> 4. before publishing profile, check if the account connected has the right to add records to this ens name
> 5. ...?

@malteish  For the **point 4**, suppose user has done **step 1 & 2 offline**, now he want's to publish profile, so he will **copy the profile details** from **.env file** and add it into the **input field in the frontend** & click on **publish profile**. **But here how do we know which ENS name has to be checked for the right to add records?** We don't have ENS name in the memory of app now.

**Comment by Bhupesh-mfsi** [comment]
Fixed
