### ISSUE TITLE
Polish

### ISSUE THREAD

**Issue by malteish** [dm3-org/dm3-ds-setup-helper#5]
Obviously, the current text-only interface is an eyesore. Make it nicer!

**Comment by malteish** [comment]
@Bhupesh-mfsi 
Please use your experience and best judgement to introduce a proper page title (e.g. Dm3 delivery service setup helper) and the dm3 corporate design:
- colors
- fonts
- favico
- ...

**Comment by Bhupesh-mfsi** [comment]
Done
