### ISSUE TITLE
ENS name mandatroy for ENS right access check & .env file name issue

### ISSUE THREAD

**Issue by Bhupesh-mfsi** [dm3-org/dm3-ds-setup-helper#9]
**Currently facing 2 barrier in delivery service setup :-**

1. We cannot download **.env file** directly on button click. For security reasons **a file without a name is not allowed to download**, so by default **.txt extension** is added to **.env** which results in **.env.txt file** download. There is only one way to fix this and that is we should name our .env file something like this **prod.env** or **dm3.env** something like this. May be this will originate a change to be done in backend or docker also.
2. While considering **offline steps to complete Step 1 and 2**, we **can't move forward with Step 3**. In step 3 **we need the ENS name** also entered by user to **check the connected account has right to add records to ENS name or not**. Even if we don't do this validation, then also **we need ENS name because useEnsResolver hook in frontend uses ensDomain to get the resolver** so we anyhow need ENS name from user. **So what should I do here? Create one more input field for user to enter ENS name again or we should avoid offline step?**

**Comment by malteish** [comment]
1. Let's call the file dm3-ds.env, and I will update the docker compose accordingly
2. I like the idea of the second ens input that is also auto-populated from step 1, but allows manual input in step 3 as well

**Comment by Bhupesh-mfsi** [comment]
Fixed
